### ISSUE TITLE
"tuple indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by oncomouse** [openlawlibrary/pygls#135]
I'm having an issue with a particular LSP client that reports a feature it doesn't actually support (which is a whole other headache), but I'm trying to use `except` to ignore the error. However, the server is instead exiting with the follow trace:

~~~
Traceback (most recent call last):
  File "/Users/apilsch/.local/bin/citation-langserver", line 8, in <module>
    sys.exit(cli())
  File "/Users/apilsch/Projects/citation-langserver/citation_langserver/cli.py", line 29, in cli
    citation_langserver.start_io()
  File "/usr/local/lib/python3.8/site-packages/pygls/server.py", line 174, in start_io
    self.loop.run_until_complete(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/pygls/server.py", line 69, in aio_readline
    proxy(b''.join(message))
  File "/usr/local/lib/python3.8/site-packages/pygls/protocol.py", line 443, in data_received
    self._procedure_handler(
  File "/usr/local/lib/python3.8/site-packages/pygls/protocol.py", line 370, in _procedure_handler
    self._handle_response(message.id, message.result, message.error)
  File "/usr/local/lib/python3.8/site-packages/pygls/protocol.py", line 349, in _handle_response
    future.set_exception(JsonRpcException.from_dict(error))
  File "/usr/local/lib/python3.8/site-packages/pygls/exceptions.py", line 44, in from_dict
    if exc_class.supports_code(error['code']):
TypeError: tuple indices must be integers or slices, not str
~~~

It looks like a tuple is getting passed to from_dict when an error is encountered, but I'm not really sure if this is something I did wrong or something wrong with the code itself.

The relevant bits from `pygls.log` are:

~~~
DEBUG:pygls.protocol:Received b'Content-Length: 138\r\n\r\n{"jsonrpc":"2.0","id":"80dbd6c7-de5f-4015-a818-fab834203bfc","error":{"code":-32601,"message":"Unhandled method workspace/configuration"}}'
DEBUG:pygls.protocol:Response message received.
DEBUG:pygls.protocol:Received error response to message 80dbd6c7-de5f-4015-a818-fab834203bfc: Object(code=-32601, message='Unhandled method workspace/configuration')
~~~

The code that's triggering this is:

~~~python
    if (
        params.capabilities.workspace is not None
        and params.capabilities.workspace.configuration is True
    ):
        try:
            ls.get_configuration(
                types.ConfigurationParams(
                    [
                        types.ConfigurationItem(
                            "", CitationLanguageServer.CONFIGURATION_SECTION
                        )
                    ]
                ),
                __update_bibliography_configuration,
            )
        except FileNotFoundError as err:
            ls.show_message(
                "File Not Found Error: {}".format(err), types.MessageType.Error
            )
~~~

Thanks!

**Comment by danixeee** [comment]
Hey, could you check if [json-example](https://github.com/openlawlibrary/pygls/blob/master/examples/json-extension/server/server.py) works with the LSP client that you are using? There are few commands which invoke `get_configuration` method and they work with VS Code client.

**Comment by oncomouse** [comment]
So it was something I was doing wrong. The `json-example` server worked perfectly.

My server was call `get_configuration` inside of the method that had been decorated with the `INITIALIZE` feature. I moved the configuration request to an `INITIALIZED` method instead, and it worked.

I guess there still might be a problem with that method getting passed a tuple instead of a dict, but my server is working again.
