### ISSUE TITLE
Pydantic FoldingRangeParams query field ValidationError

### ISSUE THREAD

**Issue by hlouzada** [openlawlibrary/pygls#153]
There seems to be an error with ``FoldingRangeParams`` as it's missing the ``query`` field. Although it's not specified by **LSP** and it might be unneeded. As the new release now uses ``pydantic`` (#151) it is requiring the ``query`` filed and throwing an error if not used.

As specified by LSP:
```java
export interface FoldingRangeParams extends WorkDoneProgressParams,
	PartialResultParams {
	/**
	 * The text document.
	 */
	textDocument: TextDocumentIdentifier;
}
``` 
See [LSP Reference](https://microsoft.github.io/language-server-protocol/specifications/specification-current/) for more details.

Error Traceback:
```py
Traceback (most recent call last):
  File "C:\Users\hendr\anaconda3\envs\ciermag-develop\lib\site-packages\pygls\protocol.py", line 144, in deserialize_message
    deserialize_params(data, get_params_type)
  File "C:\Users\hendr\anaconda3\envs\ciermag-develop\lib\site-packages\pygls\protocol.py", line 130, in deserialize_params
    data['params'] = params_type(**params)
  File "pydantic\main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FoldingRangeParams
query
  field required (type=value_error.missing)
```

An possible solution is to remove the ``query`` from the ``FoldingRangeParams`` implementation: https://github.com/openlawlibrary/pygls/blob/6ce5a5097b459622c4aff04f9196cb6309fb3736/pygls/lsp/types/language_features/folding_range.py#L52-L55

**Comment by danixeee** [comment]
@hlouzada Fix is released
