### ISSUE TITLE
Add support for setTrace Notification

### ISSUE THREAD

**Issue by karthiknadig** [openlawlibrary/pygls#162]
This is used by LS client to set the tracing level on the server. Looks like this was added in LSP 3.16 (https://microsoft.github.io/language-server-protocol/specifications/specification-current/#setTrace)
```
Failed to handle notification $/setTrace: Object(value='verbose')
Traceback (most recent call last):
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 279, in _get_handler
    return self.fm.builtin_features[feature_name]
KeyError: '$/setTrace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 282, in _get_handler
    return self.fm.features[feature_name]
KeyError: '$/setTrace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 306, in _handle_notification
    handler = self._get_handler(method_name)
  File "c:\Users\karth\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\jedilsp\pygls\protocol.py", line 284, in _get_handler
    raise JsonRpcMethodNotFound.of(feature_name)
pygls.exceptions.JsonRpcMethodNotFound
```

**Comment by danixeee** [comment]
Yes, they are constantly changing specs. Looking at the [changelog](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#version_3_16_0), I will need to update few more things.

**Comment by danixeee** [comment]
@karthiknadig Actually, everything from `3.16` needs to be added.

**Comment by karthiknadig** [comment]
@danixeee I can help with this. Should I create a issue for each item to be added? Should `3.16` work go in a separate branch?

**Comment by danixeee** [comment]
@karthiknadig I don't mind having only one issue if you plan to address all changes for `3.16`. I think I won't have time to work on it this week.

I believe you go through recently modified files [here](https://github.com/microsoft/vscode-languageserver-node/tree/main/protocol/src/common) and check everything that has `@since 3.16` in docstring. That should be easier than going through the specification document.
