### ISSUE TITLE
BrokenPipeError at shutdown

### ISSUE THREAD

**Issue by oncomouse** [openlawlibrary/pygls#179]
This may or may not be related to #173, but I'm seeing the following error whenever I shut down an LSP based on pygls 0.10.2:

~~~
DEBUG:pygls.protocol:Received b'Content-Length: 49\r\n\r\n{"method": "shutdown", "jsonrpc": "2.0", "id": 2}'
DEBUG:pygls.protocol:Request message received.
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 2, "result": null}
ERROR:pygls.protocol:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pygls/protocol.py", line 402, in _send_data
    self.transport.write(header + body)
  File "/usr/local/lib/python3.8/site-packages/pygls/server.py", line 91, in write
    self.wfile.flush()
BrokenPipeError: [Errno 32] Broken pipe
~~~

When I change the referenced line to read:

~~~python
        try:
            self.wfile.flush()
        except BrokenPipeError:
            sys.exit()
~~~

everything works. Here's the log:

~~~
DEBUG:pygls.protocol:Received b'Content-Length: 49\r\n\r\n{"id": 2, "jsonrpc": "2.0", "method": "shutdown"}'
DEBUG:pygls.protocol:Request message received.
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 2, "result": null}
INFO:pygls.server:Shutting down the server
INFO:pygls.server:Closing the event loop.
~~~

I'm using Neovim's built-in LSP, if that matters.

The LSP code (which may be configured incorrectly) is here: https://github.com/oncomouse/citation-langserver

Thanks!

**Comment by oncomouse** [comment]
I should add that the server never shuts down and will eventually start using 100% CPU.

**Comment by danixeee** [comment]
@oncomouse Could you check if https://github.com/openlawlibrary/pygls/pull/181 solves this for you? I can't reproduce it on my end.

**Comment by oncomouse** [comment]
Yes, this fixes the issue, thanks!
