### ISSUE TITLE
Unable to use pygls over websockets

### ISSUE THREAD

**Issue by alcarney** [openlawlibrary/pygls#268]
Trying to start a websocket based server I get the following error
```python
>>> from pygls.server import LanguageServer

>>> s = LanguageServer()
>>> s.start_ws('localhost', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/home/alex/Projects/pygls/pygls/server.py", line 310, in start_ws
    self.loop.run_until_complete(start_server)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/var/home/alex/Projects/esbonio/.env/lib64/python3.10/site-packages/websockets/legacy/server.py", line 1088, in __await_impl__
    server = await self._create_server()
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 1471, in create_server
    infos = await tasks.gather(*fs)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 1408, in _create_server_getaddrinfo
    infos = await self._ensure_resolved((host, port), family=family,
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 1404, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
RuntimeError: Task <Task pending name='Task-2' coro=<BaseEventLoop._create_server_getaddrinfo() running at /usr/lib64/python3.10/asyncio/base_events.py:1408> cb=[gather.<locals>._done_callback() at /usr/lib64/python3.10/asyncio/tasks.py:720]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib64/python3.10/asyncio/futures.py:385]> attached to a different loop
```

**Comment by tombh** [comment]
Just saw your "LSP Inspector" app! really nice 🤓
