### ISSUE TITLE
Broken with cattrs >= 23.2.1

### ISSUE THREAD

**Issue by sedrubal** [openlawlibrary/pygls#430]
If I tried to upgrade the dependencies of my language server but for versions of `cattrs` >= `23.2.1`, I get errors like this:

```python
Error sending data
Traceback (most recent call last):
  File "myls/.venv/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 386, in _send_data
    body = json.dumps(data, default=self._serialize_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "myls/.venv/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 309, in _serialize_message
    return self._converter.unstructure(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "myls/.venv/lib/python3.11/site-packages/cattrs/converters.py", line 238, in unstructure
    return self._unstructure_func.dispatch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cattrs generated unstructure lsprotocol.types.TextDocumentPublishDiagnosticsNotification>", line 3, in unstructure_TextDocumentPublishDiagnosticsNotification
    'params': __c_unstr_params(instance.params),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cattrs generated unstructure lsprotocol.types.PublishDiagnosticsParams>", line 4, in unstructure_PublishDiagnosticsParams
    'diagnostics': __c_unstr_diagnostics(instance.diagnostics),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 2, in unstructure_iterable
  File "", line 2, in <genexpr>
  File "<cattrs generated unstructure lsprotocol.types.Diagnostic>", line 11, in unstructure_Diagnostic
    res['codeDescription'] = __c_unstr_code_description(instance.code_description)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "myls/.venv/lib/python3.11/site-packages/cattrs/converters.py", line 965, in unstructure_optional
    return None if val is None else _handler(val)
                                    ^^^^^^^^^^^^^
  File "<cattrs generated unstructure lsprotocol.types.CodeDescription>", line 3, in unstructure_CodeDescription
    'href': instance.href,
             ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'href'
```

Do you have some recommendations or ideas how to fix it?

**Comment by alcarney** [comment]
Can you provide a sample of the data causing the issue? From the error message it looks like there could be a `CodeDescription` that doesn't have the "shape" `cattrs` is expecting to see...

Also are you using exactly `v23.2.1`? That is a known "bad" version and was excluded in [`lsprotocol` upstream](https://github.com/microsoft/lsprotocol/pull/303/files)

**Comment by alcarney** [comment]
Closing as I think this is resolved now
